FROM microsoft/dotnet:2.0-sdk
WORKDIR /sln

# copy solution
COPY *.sln ./

COPY ./CommonLib/CommonLib.csproj ./CommonLib/CommonLib.csproj
COPY ./EventCollector/EventCollector.csproj ./EventCollector/EventCollector.csproj
RUN dotnet restore

# copy and build everything else
COPY ./CommonLib ./CommonLib
COPY ./EventCollector ./EventCollector

RUN dotnet publish "./EventCollector/EventCollector.csproj" -c Release -o out
ENTRYPOINT ["dotnet", "out/EventCollector.dll"]
